name = "Predel - Create: Aeronautics"
author = "TheLeerName"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b86554821c33cf96d3f7cc460d17f647ceeaa74450c2a682ad4760d29479cac6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
