name = "Predel - Create: Aeronautics"
author = "TheLeerName"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2610331366a9fabd84a7d2530803d4a9dac6a2d8d386a20c1df8399ff7f38737"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
